### Find User by Id
GET http://localhost:3000/auth/1


### Not found User by Id
GET http://localhost:3000/auth/1000


### Find User by email
GET http://localhost:3000/auth?email=blacklacost@gmail.com


### Not found User by email
GET http://localhost:3000/auth?email=gasgfdasf@gmail.com


### Update User
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
	"email": "updated@gmail.com"
}


### Not found User when update
PATCH http://localhost:3000/auth/1000
Content-Type: application/json

{
	"email": "blacklacost@gmail.com"
}

### Delete User by id
DELETE http://localhost:3000/auth/1


### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
	"email": "blacklacost2@gmail.com",
	"password": "qwe"
}


### Signin User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
	"email": "blacklacost@gmail.com",
	"password": "qwe"
}


### Signin User fail with bad password
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
	"email": "blacklacost@gmail.com",
	"password": "qweqwe"
}


### Signin User fail with bad email
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
	"email": "blacklacostqwe@gmail.com",
	"password": "qwe"
}


### Signout User
POST http://localhost:3000/auth/signout


### Who am I?
GET http://localhost:3000/auth/whoami